name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MSNAME: api

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}    
    - name: Build the Docker image
      run: |
        docker build . \
          --build-arg MSNAME=${{ env.MSNAME }} \
          --file docker/Dockerfile \
          --tag ghcr.io/crabstash:${{ github.run_number }}
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u CrabStash --password-stdin
    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/CrabStash/auth:${{ github.run_number }}
